version: '3.8'
services:
  db:
    image: "mysql:8.0"
    container_name: sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MuntuHabitat
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"



volumes:
  db:
  keycloak:
    driver: local


